---
# this is only commented out since I'm testing on a mac..
- name: Install git
  become: true
  apt:
    name: git
    state: present



- name: We will use this username
  debug:
    msg: "{{git_author}}"


- name: We will use this email
  debug:
    msg: "{{git_email}}"



# this crap below is what I'd like to use.. 
# but apparently today isn't my lucky day, lol
# I'll try again later - I know it's  perhaps 
# because of user scoped

# - name: setup git name
#   git_config:
#     name: user.name
#     scope: global
#     value: "John Doe"

# - name: setup git user email
#   git_config:
#     name: user.email
#     scope: global
#     value: user@example.com



- name: setup git name
  shell: |
    git config --global user.email "{{git_author}}"

- name: setup git user email
  shell: |
    git config --global user.name  "{{git_email}}"