---
#this is only commented out since I'm testing on a mac..
# - name: Install git
#   apt:
#     name: git
#     state: present
#     update_cache: yes



# - name: say words
#   debug:
#     msg:  "we'll keep tweaking this to make it awesome."



# - block:
#   - name: What name to use for git commits
#     pause:
#       prompt: |
#           What's your name?
#     register: yourname
#   when: yourname is undefined


- name: We will use this username
  debug:
    msg: "{{yourname}}"
    # msg: "{{yourname.user_input if yourname.user_input is defined else yourname}}"

# - block:
#   - name: What email address to use for git commits
#     pause:
#       prompt: |
#           What's your email address?
#     register: youremail
  # when: youremail is undefined
  

