---
###########
# The following block of code is inspired from from 
# https://brave.com/linux/

- name: Install/update supporting software
  become: true
  apt:
    pkg:
      - apt-transport-https
      - curl
    state: latest


- name: adding brave browser archive to keyring
  shell: |
    sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"| sudo tee /etc/apt/sources.list.d/brave-browser-release.list


- name: Update apt cache with new browser archive
  become: true
  apt: 
    update_cache: true


- name: Install brave browser
  become: true
  apt:
    name: brave-browser
    